import Head from "next/head";
import Navbar from "../components/Navbar";

export const themeChange = () => {
  const GetElement = document.getElementById("mainWrapper");
  GetElement.classList.toggle("dark");
};

export default function Home() {
  return (
    <div className="dark" id="mainWrapper">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
    </div>
  );
}
