import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Pareners from "../components/Pareners";
import Feature1 from "../components/Feature1";
import Feature2 from "../components/Feature2";
import Video from "../components/Video";
import Collectibles from "../components/Collectibles";
import Faq from "../components/Faq";

export const themeChange = () => {
  const GetElement = document.getElementById("mainWrapper");
  GetElement.classList.toggle("dark");
};

export default function Home() {
  return (
    <div className="dark" id="mainWrapper">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white dark:bg-gray-900 dark:text-gray-100 min-h-screen">
        <Navbar />
        <Hero />
        <Pareners />
        <Feature1 />
        <Feature2 />
        <Video />
        <Collectibles />
        <Faq />
      </div>
    </div>
  );
}
